spring:
  # datasource:
  #   username: root
  #   url: jdbc:mariadb://localhost:3306/mysql
  #   driverClassName: org.mariadb.jdbc.Driver
  #   password: qwer:D1234
  thymeleaf:
    cache: "false"
  freemarker:
    cache: "false"
  mvc:
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: "true"
  config:
    import: classpath:/config.yaml
logging:
  level:
    org:
      springframework:
        nodeValue: INFO
        web: DEBUG
server:
  port: 8888
mybatis:
  type-aliases-package: com.vehicle.management.domain
