CREATE TABLE route_id ( ROUTE_ID INT PRIMARY KEY, ROUTE_NAME VARCHAR(200) );

CREATE TABLE bus_station_info ( 
ROUTE_ID INT 
, ROUTE_NAME VARCHAR(200)
, STATION_NO INT
, NODE_ID INT
, `ARS-ID` INTEGER
, STATION_NAME VARCHAR(200)
, COORDINATE_X DECIMAL(13,10)
, COORDINATE_Y DECIMAL(13,10) );
